RRT:
  verbose: 3
  output_dir: ${hydra:runtime.output_dir}
  
  start_idx: [5]
  max_expansions_per_tree: 10000
  max_configs: -1
  
  # StaGE params
  remove_expanded: true

  # Distance threshholds
  min_cost: 0.2

  # MPC actions
  tau_action: 0.25
  stepsize: [
    0.15, 0.15, 0.2, 0.25, 0.35, 0.3, 0.5, 125.0,
    0.15, 0.15, 0.2, 0.25, 0.35, 0.3, 0.5, 125.0
  ]

  # Distance measurements
  q: [0, 9]
  q_dot: [0, 9]
  q_obj_dot: 9
  P: ["obj"]
  G: ["obj"]

  obs_pos_scale: 1.0
  obs_vel_scale: 0.1
  obs_ref_err_scale: 10.0

  q_weight: 0.1

  sim_interface:
    parallel_sims: 1000
    xml_path: "configs/mujoco_/franka_emika_panda/pandas_table.xml"
    tau_sim: 0.005
    verbose: 1

    camera: "fixed_cam"
    render_w: 640
    render_h: 480

configs_path: "configs/stable/pandasTableConfigs.h5"
