policy_dir: "outputs/2026-04-01/14-51-28"
checkpoint: "checkpoints/TD3_1000000_steps"
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
alpha: .2
start_idx: -1
end_idx: -1
eval_count: 10
eval_view: "fixed_cam"
