rl_method: "TD7"
verbose: 1
total_timesteps: 3e5
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
net_arch: [256, 256]
save_freq: 5e4
batch_size: 2048

env:
  min_cost: 0.05
  max_steps: 64
  use_schedule: true
  schedule_alpha_end_step: 100000
  schedule_alpha_block: 5000
  use_csrl: true
  verbose: 1

  tau_action: 0.05
  stepsize: 0.05
  
  stable_configs_path: configs/stable/finger_ramp_big.h5
  # stable_configs_path: configs/stable/fingerRamp_onRamp.h5

  sim_interface:
    parallel_sims: 80
    xml_path: "configs/mujoco_/fingerRamp.xml"
    tau_sim: 0.005
    verbose: 1
    geoms_in_cost: [
      "l_fing", "obj"
    ]
    geoms_in_cost_weights: [
      1., 1., 1.,
      2., 2., 2.
    ]
    vels_geoms_in_cost_weights: [
      0., 0., 0.,
      0., 0., 0.
    ]
    camera: fixed_cam
    render_w: 640
    render_h: 480
