rl_method: "TD7"
verbose: 1
total_timesteps: 75000
timesteps_before_training: 5000
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
net_arch: [256, 256]
save_freq: 5e4
batch_size: 2048

env:
  min_cost: 0.01
  max_steps: 64
  use_schedule: true
  schedule_alpha_end_step: 50000
  schedule_alpha_block: 5000
  use_csrl: true
  verbose: 1

  tau_action: 0.05
  stepsize: 0.1
  
  stable_configs_path: configs/stable/double_sphere.h5
  # stable_configs_path: configs/stable/fingerRamp_onRamp.h5

  "q": [0,3]
  "q_dot": [0,3]
  "q_obj_dot": 3
  "P": ["obj"]
  "G": ["obj"]

  "q_weight": 0.2

  sim_interface:
    parallel_sims: 80
    xml_path: "configs/mujoco_/doubleSphere.xml"
    tau_sim: 0.005
    verbose: 1

    camera: fixed_cam
    render_w: 640
    render_h: 480
