rl_method: "TD7"
verbose: 1
total_timesteps: 2e6
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
net_arch: [256, 256]
save_freq: 25e4
scheduler_rate: 0.01
batch_size: 2048
TD7:
  tag: nil
  use_checkpoints: false
  timesteps_before_training: 25_000
  eval_freq: 1000
  eval_eps: 10
  max_timesteps: 2_000_000
  file_name: td7
  
  # Generic
  training_steps: 1
  learning_rate: 1e-3 #3e-4
  batch_size: 10000 #256
  buffer_size: 1e6
  discount: 0.95
  target_update_rate: 250
  exploration_noise: 0.05 # 0.025
  
  # TD3
  target_policy_noise: 0.05 # 0.025
  noise_clip: 0.1 # 0.05
  policy_freq: 2
  
  # LAP
  alpha: 0.4
  min_priority: 1
  
  # TD3+BC
  lmbda: 0.1
  
  # Checkpointing
  max_eps_when_checkpointing: 20
  steps_before_checkpointing: 75e4 
  reset_weight: 0.9
  
  # Encoder Model
  zs_dim: 512 #256 512
  enc_hdim: 512 #256 512
  enc_activ: Callable = F.elu
  
  # Critic Model
  critic_hdim: 256
  critic_activ: Callable = F.elu
  
  # Actor Model
  actor_hdim: 256
  actor_activ: Callable = F.relu
env:
  time_scaling: 1.0
  stepsize: 0.04
  max_steps: 125
  use_schedule: true
  schedule_alpha_update_rate: 100
  schedule_alpha_update_step: 0.0001
  schedule_alpha_init: 0.001
  actions_noise_sigma: 0.0
  use_vel: true
  guiding: true
  guiding_prob: 1.
  start_config_idx: -1
  target_config_idx: -1
  goal_conditioning: true
  use_vision: false
  render_w: 640
  render_h: 480
  camera_filter: "balls_mask"
  verbose: 1
  # sim:
  #   tau_sim: 0.005
  #   tau_action: 0.1
  #   interpolate_actions: true
  #   joints_are_same_as_ctrl: true
  #   use_spline_ref: false
  #   mujoco_xml: configs/mujoco_/fingerRamp.xml
  #   camera: fixed_cam
  # trajectory_data_path: "data/finger_ramp_baseline"  # TODO: either make this optional or remove stable_configs_path and mujoco_xml or idk.
  # stable_configs_path: configs/stable/fingerRamp_onRamp.h5
  # sim:
  #   tau_sim: 0.005
  #   tau_action: 0.1
  #   interpolate_actions: true
  #   joints_are_same_as_ctrl: true
  #   use_spline_ref: false
  #   mujoco_xml: configs/mujoco_/twoFingersCube.xml
  #   camera: fixed_cam
  # trajectory_data_path: "data/SpheresBoxMaxConfigs/2"  # TODO: either make this optional or remove stable_configs_path and mujoco_xml or idk.
  # stable_configs_path: configs/stable/twoFingersCube.h5
  sim:
    tau_sim: 0.005
    tau_action: 0.1
    interpolate_actions: true
    joints_are_same_as_ctrl: false
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/franka_emika_panda/pandas_table.xml
    camera: fixed_cam
  trajectory_data_path: "data/pandasTable_halffull"  # TODO: either make this optional or remove stable_configs_path and mujoco_xml or idk.
  stable_configs_path: "configs/stable/pandasTableConfigs.h5"
