RRT:
  verbose: 3
  output_dir: ${hydra:runtime.output_dir}
  
  start_idx: [1, 2, 3]
  max_expansions_per_tree: 2500
  max_configs: -1
  
  # StaGE params
  remove_expanded: true

  # Distance threshholds
  min_cost: 0.05

  # MPC actions
  tau_action: 0.05
  stepsize: 0.1

  # Distance measurements
  q: [7, 19]
  q_dot: [7, 18]
  q_obj_dot: 0
  P: [
    "FL", "FR", "RL", "RR",
  ]
  G: [
    "FL", "FR", "RL", "RR",
  ]

  obs_pos_scale: 1.0
  obs_vel_scale: 0.1
  obs_ref_err_scale: 10.0

  q_weight: 0.1

  sim_interface:
    parallel_sims: 100
    xml_path: "configs/mujoco_/unitree_go2/parkour.xml"
    tau_sim: 0.005
    verbose: 1

    njmax: 75
    nconmax: 75
    ccd_iterations: 100

    camera: "fixed_cam"
    render_w: 640
    render_h: 480

configs_path: "configs/stable/parkour.h5"
