output_dir: ${hydra:runtime.output_dir}
device: "cpu"

eval_freq: 500
eval_count: 10

agent_sampled_actions: 10
max_loops_before_training: 1000
min_buffer_size: 800000
failure_ratio: 0.0

loop_count: 3000
total_training_steps: 75000
in_loop_training_steps: 25

on_policy: true

TD7:
  batch_size: 10000
  buffer_size: 1e6
  discount: 0.95
  target_update_rate: 250
  exploration_noise: 0.15
  value_clip: [0., 1.]
  
  # TD3
  target_policy_noise: 0.05
  noise_clip: 0.1
  policy_freq: 2
  
  # LAP
  alpha: 0.4
  min_priority: 1
  
  # TD3+BC
  offline_loss: True
  lmbda: 0.1
  
  # Checkpointing
  max_eps_when_checkpointing: 20
  steps_before_checkpointing: 75e4
  reset_weight: 0.9
  
  # Encoder Model
  zs_dim: 256
  enc_hdim: 256
  encoder_lr: 1e-3
  
  # Critic Model
  critic_hdim: 256
  critic_lr: 1e-3
  
  # Actor Model
  actor_hdim: 256
  actor_lr: 1e-3

RRT:
  verbose: 0
  log_data: false
  output_dir: ${hydra:runtime.output_dir}
  
  max_expansions_per_tree: 100
  max_configs: -1
  
  # StaGE params
  remove_expanded: false

  # Distance threshholds
  min_cost: 0.01

  # MPC actions
  tau_action: 0.05
  stepsize: 0.04

  # Distance measurements
  q: [0,3]
  q_dot: [0,3]
  q_obj_dot: [3]
  P: ["obj"]
  G: ["obj"]

  obs_pos_scale: 1.0
  obs_vel_scale: 0.05
  obs_ref_err_scale: 20.0

  q_weight: 0.1

  sim_interface:
    parallel_sims: 10
    xml_path: "configs/mujoco_/doubleSphere.xml"
    tau_sim: 0.005
    verbose: 1

    camera: "fixed_cam"
    render_w: 640
    render_h: 480

configs_path: "configs/stable/double_sphere_clean.h5"
