output_dir: ${hydra:runtime.output_dir}
device: "cpu"

checkpoint_freq: 10
eval_freq: 10

agent_sampled_actions: 10
max_loops_before_training: 5

loop_count: 100
in_loop_training_steps: 100

TD7:
  batch_size: 16000
  buffer_size: 4e6
  discount: 0.99
  target_update_rate: 250
  exploration_noise: 0.05
  value_clip: [0., 1.]
  
  # TD3
  target_policy_noise: 0.05
  noise_clip: 0.1
  policy_freq: 2
  
  # LAP
  alpha: 0.4
  min_priority: 1
  
  # TD3+BC
  lmbda: 0.1
  
  # Checkpointing
  max_eps_when_checkpointing: 20
  steps_before_checkpointing: 75e4 
  reset_weight: 0.9
  
  # Encoder Model
  zs_dim: 512
  enc_hdim: 512
  encoder_lr: 1e-3
  
  # Critic Model
  critic_hdim: 512
  critic_lr: 1e-3
  
  # Actor Model
  actor_hdim: 512
  actor_lr: 1e-3

RRT:
  verbose: 3
  log_data: false
  output_dir: ${hydra:runtime.output_dir}
  
  max_expansions_per_tree: 10000
  max_configs: -1
  
  # StaGE params
  remove_expanded: false

  # Distance threshholds
  min_cost: 0.1

  # MPC actions
  tau_action: 0.1
  stepsize: 0.5

  # Distance measurements
  q: [7,36]
  q_dot: [6,35]
  q_obj_dot: 0
  P: [
    "pelvis",
    "left_ankle_roll_joint", "right_ankle_roll_joint",
    "left_rubber_hand_0", "right_rubber_hand_0",
    "box_marker_0", "box_marker_1", "box_marker_2"
  ]
  G: [
    "box_marker_0", "box_marker_1", "box_marker_2"
  ]
  obs_pos_scale: 1.0
  obs_vel_scale: 0.1
  obs_ref_err_scale: 10.0

  q_weight: 0.0

  sim_interface:
    parallel_sims: 50
    xml_path: "configs/mujoco_/unitree_g1/box_scene.xml"
    tau_sim: 0.005
    verbose: 1

    camera: "fixed_cam"
    render_w: 640
    render_h: 480

configs_path: "configs/stable/humanoid_box_grasps.h5"
