policy_dir: "data/policies/sac_random_guidance_wrong_time_scaling"
checkpoint: "checkpoints/SAC_1250000_steps"
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
start_idx: 11
end_idx: 25
eval_view: "fixed_cam"
