env:
  start_config_idx: 80
  target_config_idx: 32
  max_steps: 50
  stepsize: .1
  tau: .1
  actions_noise_sigma: -1
  use_vel: False
  guiding: True
  dataset: "trees"

checkpoint_dir: "checkpoints/trained_rl_policy.zip"
output_dir: ${hydra:runtime.output_dir}
