policy_dir: "data/policies/sac_more_paths_timewarp_less_noise"
checkpoint: "checkpoints/SAC_2500000_steps"
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
start_idx: -1
end_idx: -1
eval_count: 10
eval_view: "fixed_cam"
