rl_method: "PPO"
verbose: 1
total_timesteps: 2e7
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
net_arch: [256, 256]
env:
  stepsize: .1
  max_steps: 50
  actions_noise_sigma: -1
  use_vel: True
  guiding: True
  start_config_idx: -1
  target_config_idx: -1
  goal_conditioning: True
  use_vision: False
  camera_filter: "blue_ball_params"
  verbose: 0
  sim:
    tau_sim: 0.001
    tau_action: 0.5
    interpolate_actions: True
    joints_are_same_as_ctrl: true
    mujoco_xml: "configs/fingerRamp.xml"
    camera: wrist_cam
  trajectory_data_path: "data/fingerRamp_full"
  stable_configs_path: "configs/fingerRamp_onRamp.h5"
