rl_method: "SAC"
verbose: 1
total_timesteps: 2e7
output_dir: ${hydra:runtime.output_dir}
device: "cuda"
net_arch: [256, 256]
save_freq: 25e4
env:
  stepsize: .03
  max_steps: 125
  actions_noise_sigma: 0.01
  use_vel: False
  guiding: True
  guiding_prob: 0.5
  start_config_idx: -1
  target_config_idx: -1
  goal_conditioning: True
  use_vision: True
  camera_filter: "balls_mask"
  verbose: 1
  sim:
    tau_sim: 0.001
    tau_action: 0.1
    interpolate_actions: True
    joints_are_same_as_ctrl: true
    mujoco_xml: "configs/fingerRamp.xml"
    camera: wrist_cam
  trajectory_data_path: "data/fingerRamp_full"
  stable_configs_path: "configs/fingerRamp_onRamp.h5"
