RRT:
  max_nodes: 20000
  min_cost: 2e-2
  stepsize: .3
  verbose: 1
  target_prob: .2
  sample_uniform: False
  warm_start: False
  threading: True
  start_idx: 6
  end_idx: 1
  sample_count: 1000
  sampling_strategy: "rs"
  output_dir: ${hydra:runtime.output_dir}
  q_mask: []
  tau_sim: 0.001
  tau_action: 0.1

configs_path: "configs/pandasTable_ball.h5"
mujoco_xml: "configs/franka_emika_panda/scene.xml"
